# Starter pipeline

trigger:
- manual

pool: devopsdeploy

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Kubernetes@0
  displayName: 'kubectl exec -it rm -r'
  inputs:
    kubernetesServiceConnection: jhubpockubectl
    namespace: jhub
    command: exec
    arguments: 'jupyter-$(USER) -- /bin/bash -c "rm -rf $(DIRECTORY)'
    kubectlOutput: 'available_pods'
- task: Kubernetes@0
  displayName: 'kubectl exec -it git clone'
  inputs:
    kubernetesServiceConnection: jhubpockubectl
    namespace: jhub
    command: exec
    arguments: 'jupyter-$(USER) -- /bin/bash -c "git clone \"$(GITHUB_REPO)\""'
    kubectlOutput: 'available_pods'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
